// <auto-generated />
using Cliente.Entities.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cliente.Entities.Migrations
{
    [DbContext(typeof(RepositoryContextFactory))]
    partial class RepositoryContextFactoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Cliente")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Cliente.Entities.Consumidor", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes", "Cliente");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Nombre = "Cliente 1"
                        },
                        new
                        {
                            ClienteId = 2,
                            Nombre = "Cliente 2"
                        },
                        new
                        {
                            ClienteId = 3,
                            Nombre = "Cliente 3"
                        },
                        new
                        {
                            ClienteId = 4,
                            Nombre = "Cliente 4"
                        },
                        new
                        {
                            ClienteId = 5,
                            Nombre = "Cliente 5"
                        },
                        new
                        {
                            ClienteId = 6,
                            Nombre = "Cliente 6"
                        },
                        new
                        {
                            ClienteId = 7,
                            Nombre = "Cliente 7"
                        },
                        new
                        {
                            ClienteId = 8,
                            Nombre = "Cliente 8"
                        },
                        new
                        {
                            ClienteId = 9,
                            Nombre = "Cliente 9"
                        },
                        new
                        {
                            ClienteId = 10,
                            Nombre = "Cliente 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
